name: Ethiopia Tender Watcher

on:
  schedule:
    - cron: '*/15 * * * *'   # every 15 minutes
  workflow_dispatch:

permissions:
  contents: write  # allow committing updated state/seen.json

concurrency:
  group: tenderbot
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
      # fetch-depth 0 so we can commit back
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run watcher
        env:
          ALERT_TO: ${{ secrets.ALERT_TO }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          HEARTBEAT_ENABLE: "true"
          HEARTBEAT_HOUR_UTC: "6"
        run: |
          python main.py

      - name: Commit state if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "tenderbot"
            git config user.email "actions@users.noreply.github.com"
            git add state/seen.json
            git commit -m "chore(state): update seen.json [skip ci]"
            git push
          else
            echo "No state changes to commit."
          fi
